const i18Obj = {
    "en": {
            "Skills": 'Skills',
            "Portfolio": 'Portfolio',
            "Video": 'Video',
            "Price": 'Price',
            "Contacts": 'Contacts',
            "hero-title": 'Alexa Rise',
            "hero-cite": 'Save sincere emotions, romantic feelings and happy moments of life together with professional photographer Alexa Rise',
            "hero-btn": 'Hire me',
            "Skills-item-1-1": 'Digital photography',
            "Skills-item-1-2": 'High-quality photos in the studio and on the nature',
            "Skills-item-2-1": 'Video shooting',
            "Skills-item-2-2": 'Capture your moments so that they always stay with you',
            "Skills-item-3-1": 'Retouch',
            "Skills-item-3-2": 'I strive to make photography surpass reality',
            "Skills-item-4-1": 'Audio',
            "Skills-item-4-2": 'Professional sounds recording for video, advertising, portfolio',
            "Winter": 'Winter',
            "Spring": 'Spring',
            "Summer": 'Summer',
            "Autunm": 'Autunm',
            "Price-title-1": 'Standard',
            "Price-service-1":'500$',
            "Price-service-span-1-1": 'One location',
            "Price-service-span-1-2": '120 photos in color',
            "Price-service-span-1-3": '12 photos in retouch',
            "Price-service-span-1-4": 'Readiness 2-3 weeks',
            "Price-service-span-1-5": 'Make up, visage',
            "Price-btn": 'Order shooting',
            "Price-title-2": 'Premium',
            "Price-service-2": '700$',
            "Price-service-span-2-1": 'One or two locations',
            "Price-service-span-2-2": '200 photos in color',
            "Price-service-span-2-3": '20 photos in retouch',
            "Price-service-span-2-4": 'Readiness 1-2 weeks',
            "Price-service-span-2-5": 'Make up, visage',
            "Price-btn": 'Order shooting',
            "Price-title-3": 'Gold',
            "Price-service-3": '1000$',
            "Price-service-span-3-1": 'Three locations or more',
            "Price-service-span-3-2": '300 photos in color',
            "Price-service-span-3-3": '50 photos in retouch',
            "Price-service-span-3-4": 'Readiness 1 week',
            "Price-service-span-3-5": 'Make up, visage, hairstyle',
            "Price-btn": 'Order shooting',
            "Contact-title": 'Contact me'
            }, 
        "ru": {
            "Skills": 'Навыки',
            "Portfolio": 'Портфолио',
            "Video": 'Видео',
            "Price": 'Цены',
            "Contacts": 'Контакты',
            "hero-title": 'Алекса Райс',
            "hero-cite": 'Сохраните искренние эмоции, романтические переживания и счастливые моменты жизни вместе с профессиональным фотографом',
            "hero-btn": 'Пригласить',
            "Skills-item-1-1": 'Фотография',
            "Skills-item-1-2": 'Высококачественные фото в студии и на природе',
            "Skills-item-2-1": 'Видеосъемка',
            "Skills-item-2-2": 'Запечатлите лучшие моменты, чтобы они всегда оставались с вами',
            "Skills-item-3-1": 'Ретушь',
            "Skills-item-3-2": 'Я стремлюсь к тому, чтобы фотография превосходила реальность',
            "Skills-item-4-1": 'Звук',
            "Skills-item-4-2": 'Профессиональная запись звука для видео, рекламы, портфолио',
            "Winter": 'Зима',
            "Spring": 'Весна',
            "Summer": 'Лето',
            "Autunm": 'Осень',
            "Price-title-1": 'Standard',
            "Price-service-1":'500$',
            "Price-service-span-1-1": 'Одна локация',
            "Price-service-span-1-2": '120 цветных фото',
            "Price-service-span-1-3": '12 отретушированных фото',
            "Price-service-span-1-4": 'Готовность через 2-3 недели',
            "Price-service-span-1-5": 'Макияж, визаж',
            "Price-btn": 'Заказать съемку',
            "Price-title-2": 'Premium',
            "Price-service-2": '700$',
            "Price-service-span-2-1": 'Одна-две локации',
            "Price-service-span-2-2": '200 цветных фото',
            "Price-service-span-2-3": '20 отретушированных фото',
            "Price-service-span-2-4": 'Готовность через 1-2 недели',
            "Price-service-span-2-5": 'Макияж, визаж',
            "Price-btn": 'Заказать съемку',
            "Price-title-3": 'Gold',
            "Price-service-3": '1000$',
            "Price-service-span-3-1": 'Три локации и больше',
            "Price-service-span-3-2": '300 цветных фото',
            "Price-service-span-3-3": '50 отретушированных фото',
            "Price-service-span-3-4": 'Готовность через 1 неделю',
            "Price-service-span-3-5": 'Макияж, визаж, прическа',
            "Price-btn": 'Заказать съемку',
            "Contact-title": 'Свяжитесь со мной'
            }
}

export default i18Obj;